class Store:
    """
    Helper class to provide a centralised store for CONSTANTS and globals
    """

    # Static class variables, referred to by Store.whatever
    # https://docs.python.org/3/faq/programming.html#how-do-i-create-static-class-data-and-static-class-methods

    # CONSTANTS
    # ABC WEATHER VIDEO - scraping
    ABC_URL = "https://www.abc.net.au/news/newschannel/news-in-90-seconds"

    # BOM - JSON API
    BOM_URL = 'http://www.bom.gov.au'
    BOM_API_URL = 'https://api.weather.bom.gov.au/v1'
    BOM_API_LOCATIONS_URL = BOM_API_URL + '/locations'
    # BOM - RADARS - FTP
    BOM_RADAR_FTPSTUB = "ftp://anonymous:someone%40somewhere.com@ftp.bom.gov.au//anon/gen/radar/"
    BOM_RADAR_BACKGROUND_FTPSTUB = "ftp://anonymous:someone%40somewhere.com@ftp.bom.gov.au//anon/gen/radar_transparencies/"
    BOM_RADAR_HTTPSTUB = "http://www.bom.gov.au/products/radar_transparencies/"

    # The below list is generated using my scraper: python3 resources/lib/bom/bom_radar_scrape_latest.py
    # Just cut and paste the output of that below....
    # The master URL is: http://www.bom.gov.au/australia/radar/about/radar_site_info.shtml
    # Can cross-check with: https://github.com/theOzzieRat/bom-radar-card/blob/master/src/bom-radar-card.ts around line 130

    # Last update: 2026-03-16
    # (Python) Automatically generated by bom_radar_scraper_latest.py from http://reg.bom.gov.au/australia/radar/about/radar_site_info.shtml
    BOM_RADAR_LOCATIONS = [
        # http://www.bom.gov.au/australia/radar/info/nsw_info.shtml
        (-29.96, 146.81, "Brewarrina", "IDR933"),
        (-35.66, 149.51, "Canberra (Captain's Flat)", "IDR403"),
        (-29.62, 152.97, "Grafton", "IDR283"),
        (-33.55, 145.52, "Hillston", "IDR943"),
        (-29.50, 149.85, "Moree", "IDR533"),
        (-31.0240, 150.1915, "Namoi (Blackjack Mountain)", "IDR693"),
        (-32.730, 152.027, "Newcastle", "IDR043"),
        (-29.033, 167.933, "Norfolk Island", "IDR623"),
        (-33.701, 151.210, "Sydney (Terrey Hills)", "IDR713"),
        (-35.17, 147.47, "Wagga Wagga", "IDR553"),
        (-34.264, 150.874, "Wollongong (Appin)", "IDR033"),
        (-32.74, 148.70, "Yeoval", "IDR963"),
        # http://www.bom.gov.au/australia/radar/info/vic_info.shtml
        (-37.86, 144.76, "Melbourne", "IDR023"),
        (-34.28, 141.59, "Mildura", "IDR973"),
        (-37.89, 147.56, "Bairnsdale", "IDR683"),
        (-35.99, 142.01, "Rainbow", "IDR953"),
        (-36.03, 146.03, "Yarrawonga", "IDR493"),
        # http://www.bom.gov.au/australia/radar/info/qld_info.shtml
        (-19.88, 148.08, "Bowen", "IDR243"),
        (-27.718, 153.240, "Brisbane (Mt. Stapylton)", "IDR663"),
        (-16.82, 145.68, "Cairns", "IDR193"),
        (-23.5494, 148.2392, "Emerald (Central Highlands)", "IDR723"),
        (-23.86, 151.26, "Gladstone", "IDR233"),
        (-18.99, 144.99, "Greenvale", "IDR743"),
        (-25.957, 152.577, "Gympie (Mt Kanigan)", "IDR083"),
        (-23.43, 144.29, "Longreach", "IDR563"),
        (-21.12, 149.22, "Mackay", "IDR223"),
        (-27.61, 152.54, "Marburg", "IDR503"),
        (-16.67, 139.17, "Mornington Island", "IDR363"),
        (-20.7114, 139.5553, "Mount Isa", "IDR753"),
        (-20.75, 143.14, "Richmond", "IDR1073"),
        (-25.696, 149.898, "Taroom", "IDR983"),
        (-27.2740, 151.9930, "Toowoomba", "IDR1083"),
        (-26.44, 147.35, "Warrego", "IDR673"),
        (-12.67, 141.92, "Weipa", "IDR783"),
        (-16.288, 149.965, "Willis Island", "IDR413"),
        # http://www.bom.gov.au/australia/radar/info/wa_info.shtml
        (-34.94, 117.80, "Albany", "IDR313"),
        (-17.95, 122.23, "Broome", "IDR173"),
        (-24.88, 113.67, "Carnarvon", "IDR053"),
        (-24.88, 113.67, "Carnarvon", "IDR1143"),
        (-20.65, 116.69, "Dampier", "IDR153"),
        (-31.78, 117.95, "South Doodlakine", "IDR583"),
        (-33.83, 121.89, "Esperance", "IDR323"),
        (-28.80, 114.70, "Geraldton", "IDR063"),
        (-25.03, 128.30, "Giles", "IDR443"),
        (-18.23, 127.66, "Halls Creek", "IDR393"),
        (-30.79, 121.45, "Kalgoorlie-Boulder", "IDR483"),
        (-20.99, 116.87, "Karratha", "IDR1113"),
        (-22.10, 114.00, "Learmonth", "IDR293"),
        (-33.097, 119.009, "Newdegate", "IDR383"),
        (-32.39, 115.87, "Perth (Serpentine)", "IDR703"),
        (-31.93, 115.98, "Perth Airport", "IDR263"),
        (-20.37, 118.63, "Port Hedland", "IDR163"),
        (-30.36, 116.29, "Watheroo", "IDR793"),
        (-15.45, 128.12, "Wyndham", "IDR073"),
        # http://www.bom.gov.au/australia/radar/info/sa_info.shtml
        (-34.617, 138.469, "Adelaide (Buckland Park)", "IDR643"),
        (-35.33, 138.50, "Adelaide (Sellicks Hill)", "IDR463"),
        (-32.13, 133.70, "Ceduna", "IDR333"),
        (-37.75, 140.77, "Mt Gambier", "IDR143"),
        (-31.16, 136.80, "Woomera", "IDR273"),
        # http://www.bom.gov.au/australia/radar/info/tas_info.shtml
        (-43.1122, 147.8061, "Hobart (Mt Koonya)", "IDR763"),
        (-41.181, 145.579, "West Takone", "IDR523"),
        (-42.83, 147.51, "Hobart Airport", "IDR373"),
        # http://www.bom.gov.au/australia/radar/info/nt_info.shtml
        (-23.82, 133.90, "Alice Springs", "IDR253"),
        (-12.46, 130.93, "Darwin/Berrimah", "IDR633"),
        (-12.27, 136.82, "Gove", "IDR1123"),
        (-14.51, 132.45, "Katherine/Tindal", "IDR423"),
        (-11.6494, 133.38, "Warruwi", "IDR773"),
    ]

    # RADAR location and range lookups...
    # The -1 here removes the range from the radar (1,2,3,4 at the end of IDR02, for example)
    RADAR_LOCATION = {code[:-1]: name for _, _, name, code in BOM_RADAR_LOCATIONS}
    # Manually add the name for this special radar that is not returned in the scraped list
    RADAR_LOCATION["IDR0000"] = "Australia"
    # The last digit indicates the range of the radar
    RADAR_RANGE_MAP = {
        "1": "512km",
        "2": "256km",
        "3": "128km",
        "4": "64km",
    }
    # Convenience method to return the range if known (including a range of 'National' for the whole-country radar)
    @staticmethod
    def RADAR_RANGE(radar_code):
        if radar_code == "IDR00004":
            return "National"
        return Store.RADAR_RANGE_MAP.get(radar_code[-1], "?Range")

    DAYS = {"Mon": "Monday",
            "Tue": "Tuesday",
            "Wed": "Wednesday",
            "Thu": "Thursday",
            "Fri": "Friday",
            "Sat": "Saturday",
            "Sun": "Sunday"}

    # (Updated 2026-03)
    # BOM API icon_descriptor → Kodi weather code mapping
    # BOM source: api.weather.bom.gov.au (modern REST API, icon_descriptor field)
    # Kodi codes: https://kodi.wiki/view/Weather_addons#Weather_Codes
    #
    # Notes:
    #   - Modern BOM API descriptors use underscores (e.g. partly_cloudy)
    #   - Legacy FTP/XML descriptors (e.g. cloud_increasing, rain_developing) are
    #     retained below for backwards compatibility but marked accordingly
    #   - Day/night split: day uses sun icons (32=sunny, 34=fair/partly sunny),
    #     night uses moon icons (31=clear night, 33=fair night)

    WEATHER_CODES = {
        # === Modern BOM REST API icon_descriptor values ===
        'sunny': '32',  # Sunny
        'clear': '32',  # Clear (daytime = sunny)
        'mostly_sunny': '34',  # Mostly sunny / fair (day)
        'partly_cloudy': '30',  # Partly cloudy (day)
        'cloudy': '26',  # Cloudy
        'overcast': '26',  # Overcast / cloudy
        'haze': '21',  # Haze
        'hazy': '21',  # Hazy
        'fog': '20',  # Fog
        'frost': '25',  # Frost (cold/clear)
        'dust': '19',  # Dust
        'dusty': '19',  # Dusty
        'wind': '23',  # Windy
        'windy': '23',  # Windy
        'light_shower': '11',  # Light shower
        'light_showers': '11',  # Light showers
        'shower': '11',  # Shower
        'showers': '11',  # Showers
        'heavy_shower': '12',  # Heavy shower
        'heavy_showers': '12',  # Heavy showers
        'light_rain': '11',  # Light rain (closer to showers than pouring)
        'rain': '40',  # Rain
        'heavy_rain': '40',  # Heavy rain
        'snow': '16',  # Snow
        'storm': '38',  # Storm / thunderstorm
        'storms': '38',  # Storms
        'tropical_cyclone': '1',  # Tropical cyclone
        'cyclone': '1',  # Cyclone

        # === Legacy BOM FTP/XML descriptors (retained for compatibility) ===
        'clearing_shower': '39',
        'cloud_and_wind_increasing': '23',
        'cloud_increasing': '26',
        'drizzle': '9',  # was '11' (showers); drizzle = code 9
        'drizzle_clearing': '39',
        'fog_then_sunny': '34',
        'frost_then_sunny': '34',
        'heavy_showers': '12',
        'increasing_sunshine': '30',
        'late_shower': '39',
        'late_thunder': '37',
        'mostly_cloudy': '28',  # was '26'; 28=mostly cloudy day
        'possible_shower': '11',
        'possible_thunderstorm': '37',
        'rain_and_snow': '5',
        'rain_clearing': '39',
        'rain_developing': '12',
        'rain_tending to_snow': '5',
        'showers_easing': '11',
        'showers_increasing': '11',
        'snowfalls_clearing': '5',
        'snow_developing': '13',
        'snow_showers': '41',
        'snow_tending to_rain': '5',
        'thunderstorms': '38',
        'thunderstorms_clearing': '37',
        'wind_and_rain_increasing': '2',
        'wind_and_showers_easing': '11',
        'windy_with_rain': '2',
        'windy_with_showers': '2',
        'windy_with_snow': '43',

        # === Fallback ===
        'unknown': 'na',
        'nt_unknown': 'na',
    }

    WEATHER_CODES_NIGHT = {
        # === Modern BOM REST API icon_descriptor values ===
        'sunny': '31',  # Clear night (shouldn't appear at night but safe fallback)
        'clear': '31',  # Clear night
        'mostly_sunny': '33',  # Fair night
        'partly_cloudy': '29',  # Partly cloudy (night)
        'cloudy': '27',  # Mostly cloudy (night) — no pure 'cloudy night' code, 27 is closest
        'overcast': '29',  # Overcast night
        'haze': '21',  # Haze (no day/night variant)
        'hazy': '21',  # Hazy
        'fog': '20',  # Fog (no day/night variant)
        'frost': '25',  # Frost / cold
        'dust': '19',  # Dust
        'dusty': '19',  # Dusty
        'wind': '27',  # Windy night (27=mostly cloudy night, no pure windy night)
        'windy': '27',
        'light_shower': '45',  # Scattered showers (night)
        'light_showers': '45',
        'shower': '45',
        'showers': '45',
        'heavy_shower': '45',  # No heavy shower night code; 45 is best available
        'heavy_showers': '45',
        'light_rain': '45',  # Light rain night
        'rain': '45',  # Rain night
        'heavy_rain': '45',  # Heavy rain night (no specific code; 45 is showers night)
        'snow': '46',  # Snow/snow showers (night)
        'storm': '47',  # Scattered thunderstorms (night)
        'storms': '47',
        'tropical_cyclone': '1',  # No night variant
        'cyclone': '1',

        # === Legacy BOM FTP/XML descriptors ===
        'clearing_shower': '45',
        'cloud_and_wind_increasing': '27',
        'cloud_increasing': '27',
        'drizzle': '45',
        'drizzle_clearing': '45',
        'fog_then_sunny': '33',
        'frost_then_sunny': '33',
        'increasing_sunshine': '31',
        'late_shower': '45',
        'late_thunder': '47',
        'mostly_cloudy': '27',
        'possible_shower': '45',
        'possible_thunderstorm': '47',
        'rain_and_snow': '46',
        'rain_clearing': '45',
        'rain_developing': '45',
        'rain_tending to_snow': '45',
        'showers_easing': '45',
        'showers_increasing': '45',
        'snowfalls_clearing': '46',
        'snow_developing': '46',
        'snow_showers': '46',
        'snow_tending to_rain': '46',
        'thunderstorms': '47',
        'thunderstorms_clearing': '47',
        'thunder-storms': '47',  # Hyphenated variant seen in some BOM responses
        'wind_and_rain_increasing': '45',
        'wind_and_showers_easing': '45',
        'windy_with_rain': '45',
        'windy_with_showers': '45',
        'windy_with_snow': '46',

        # === Fallback ===
        'unknown': 'na',
        'nt_unknown': 'na',
    }

    # Just a store!
    def __init__(self):
        pass
